name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  wheels:
    uses: ./.github/workflows/wheels.yml

  publish:
    name: Publish to PyPI
    needs: wheels
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*"
          merge-multiple: true
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
